import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageProgress from "@/components/PageProgress";

const BASE_URL = "https://smart-convertor.vercel.app";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "SmartConverter – Free Online File Converter",
    template: "%s | SmartConverter",
  },
  description:
    "Free online file converter. Convert PDF, images & documents in your browser. No signup, no uploads, no limits. 24 tools — 100% private.",
  keywords: [
    "free pdf converter online",
    "compress pdf online free",
    "convert images to pdf",
    "pdf to word converter",
    "image compressor online",
    "pdf merge online",
    "pdf split online",
    "ocr image to text",
    "qr code generator",
    "json formatter online",
    "base64 encoder decoder",
    "browser based file converter",
  ],
  authors:         [{ name: "SmartConverter", url: BASE_URL }],
  creator:         "SmartConverter",
  publisher:       "SmartConverter",
  applicationName: "SmartConverter",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Next.js auto-generates /icon.png (512×512) and /apple-icon.png (180×180)
  // from app/icon.tsx and app/apple-icon.tsx — no manual icon config needed
  verification: {
    google: "B74z6DyxgoGRoMNAF5F0Ou1vAiVG05hoHHqppna-swM",
  },
  openGraph: {
    type:        "website",
    locale:      "en_US",
    url:         BASE_URL,
    siteName:    "SmartConverter",
    title:       "SmartConverter – Free Online File Converter",
    description: "Convert PDF, images & documents free in your browser. No signup, no uploads. 24 tools, 100% private.",
    // Next.js auto-generates /opengraph-image.png from app/opengraph-image.tsx
  },
  twitter: {
    card:        "summary_large_image",
    title:       "SmartConverter – Free Online File Converter",
    description: "Convert PDF, images & documents free in your browser. No signup, no uploads. 24 tools, 100% private.",
    // Twitter picks up the opengraph-image automatically
  },
  alternates: {
    canonical: BASE_URL,
  },
};

// ── Structured Data ──────────────────────────────────────────────────────────
// Google uses Organization.logo (PNG, absolute URL) to determine the
// site name and icon shown in search results — NOT the favicon.
// Using /icon.png (generated by app/icon.tsx at 512×512).

const orgSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "SmartConverter",
  alternateName: "Smart Converter",
  url: BASE_URL,
  logo: {
    "@type": "ImageObject",
    url: `${BASE_URL}/icon.png`,   // PNG — required by Google for Knowledge Panel
    width: 512,
    height: 512,
    caption: "SmartConverter logo",
  },
  sameAs: [BASE_URL],
};

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "SmartConverter",
  alternateName: "Smart Converter",
  url: BASE_URL,
  description:
    "Free browser-based file converter. Convert PDF, images and documents with 24 tools. No uploads, no signup.",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${BASE_URL}/?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
          Explicit <link> tags ensure our favicon overrides any Vercel defaults.
          /icon.png is served by Next.js from app/icon.tsx (512×512 PNG).
          /apple-icon.png is served from app/apple-icon.tsx (180×180 PNG).
        */}
        <link rel="icon"             href="/icon.png" type="image/png" sizes="512x512" />
        <link rel="icon"             href="/favicon.ico" sizes="32x32" />
        <link rel="apple-touch-icon" href="/apple-icon.png" sizes="180x180" />
        <link rel="shortcut icon"    href="/favicon.ico" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body>
        <ThemeProvider>
          <div
            className="min-h-screen flex flex-col"
            style={{ background: "var(--background)", color: "var(--foreground)" }}
          >
            <PageProgress />
            <Navbar />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
